name: second-level-workflow
on:
  workflow_call:
    inputs:
      VAR1:
        required: true
        type: string
      VAR2:
        required: true
        type: string
      VAR3:
        required: true
        type: string
    secrets:
      SECRET1:
        required: true
      SECRET2:
        required: true
      SECRET3:
        required: true
jobs:
  show-env:
    name: Show Environment
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print secrets
        run: |
          echo "SECRET1=${{ secrets.SECRET1 }}"
          echo "SECRET2=${{ secrets.SECRET2 }}"
          echo "SECRET3=${{ secrets.SECRET3 }}"
      
      - name: Print inputs
        run: |
          echo "VAR1=${{ inputs.VAR1 }}"
          echo "VAR2=${{ inputs.VAR2 }}"
          echo "VAR3=${{ inputs.VAR3 }}"
  call-level-3:
    name: Second Level Workflow
    uses: ./.github/workflows/third-level-workflow.yml
    with:
      VAR1: ${{ inputs.VAR1 }}
      VAR2: ${{ inputs.VAR2 }}
      VAR3: ${{ inputs.VAR3 }}
    secrets:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
      SECRET3: ${{ secrets.SECRET3 }}