name: second-level-workflow
on:
  workflow_call:
    inputs:
      VAR1:
        required: true
        type: string
      VAR2:
        required: true
        type: string
      VAR3:
        required: true
        type: string
    secrets:
      SECRET1:
        required: true
      SECRET2:
        required: true
      SECRET3:
        required: true
jobs:
  process-vars:
    name: Process Vars
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      SECRET1: ${{ steps.prepare-secrets.outputs.SECRET1 }}
      SECRET2: ${{ steps.prepare-secrets.outputs.SECRET2 }}
      SECRET3: ${{ steps.prepare-secrets.outputs.SECRET3 }}
      VAR1: ${{ steps.prepare-vars.outputs.VAR1 }}
      VAR2: ${{ steps.prepare-vars.outputs.VAR2 }}
      VAR3: ${{ steps.prepare-vars.outputs.VAR3 }}
    steps:
      - name: Prepare secrets
        id: prepare-secrets
        run: |
          echo "SECRET1=${{ secrets.SECRET1 }}" >> $GITHUB_OUTPUT
          echo "SECRET2=${{ secrets.SECRET2 }}" >> $GITHUB_OUTPUT
          echo "SECRET3=${{ secrets.SECRET3 }}" >> $GITHUB_OUTPUT
      - name: Prepare vars
        id: prepare-vars
        run: |
          echo "VAR1=${{ vars.VAR1 }}" >> $GITHUB_OUTPUT
          echo "VAR2=${{ vars.VAR2 }}" >> $GITHUB_OUTPUT
          echo "VAR3=${{ vars.VAR3 }}" >> $GITHUB_OUTPUT
  show-env:
    name: Show Environment
    runs-on: ubuntu-latest
    needs: process-vars
    steps:
      - name: Print secrets
        run: |
          echo "SECRET1=${{ needs.process-vars.outputs.SECRET1 }}"
          echo "SECRET2=${{ needs.process-vars.outputs.SECRET2 }}"
          echo "SECRET3=${{ needs.process-vars.outputs.SECRET3 }}"
      
      - name: Print inputs
        run: |
          echo "VAR1=${{ needs.process-vars.outputs.VAR1 }}"
          echo "VAR2=${{ needs.process-vars.outputs.VAR2 }}"
          echo "VAR3=${{ needs.process-vars.outputs.VAR3 }}"
  call-level-3:
    name: Second Level Workflow
    uses: ./.github/workflows/third-level-workflow.yml
    needs: process-vars
    with:
      VAR1: ${{ needs.process-vars.outputs.VAR1 }}
      VAR2: ${{ needs.process-vars.outputs.VAR2 }}
      VAR3: ${{ needs.process-vars.outputs.VAR3 }}
    secrets:
      SECRET1: ${{ needs.process-vars.outputs.SECRET1 }}
      SECRET2: ${{ needs.process-vars.outputs.SECRET2 }}
      SECRET3: ${{ needs.process-vars.outputs.SECRET3 }}