name: second-level-workflow
on:
  workflow_call:
    inputs:
      deploy-environment:
        required: true
        type: string
    secrets:
      SECRET1:
        required: true
      SECRET2:
        required: true
      SECRET3:
        required: true
jobs:
  show-env:
    name: Show Environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-environment }}
    steps:
      - run: |
          echo "SECRET1=${{ secrets.SECRET1 }}"
          echo "SECRET2=${{ secrets.SECRET2 }}"
          echo "SECRET3=${{ secrets.SECRET3 }}"
      
      - name: Print inputs
        run: |
          echo "VAR1=${{ vars.VAR1 }}"
          echo "VAR2=${{ vars.VAR2 }}"
          echo "VAR3=${{ vars.VAR3 }}"
  call-level-3:
    name: Second Level Workflow
    uses: ./.github/workflows/third-level-workflow.yml
    with:
      deploy-environment: ${{ inputs.deploy-environment }}
    secrets:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
      SECRET3: ${{ secrets.SECRET3 }}