name: third-level-workflow
on:
  workflow_call:
    inputs:
      deploy-environment:
        required: true
        type: string
    secrets:
      SECRET1:
        required: true
      SECRET2:
        required: true
      SECRET3:
        required: true
jobs:
  show-env:
    name: Show Environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-environment }}
    steps:
      - name: Print secrets
        run: |
          echo "SECRET1=${{ secrets.SECRET1 }}"
          echo "SECRET2=${{ secrets.SECRET2 }}"
          echo "SECRET3=${{ secrets.SECRET3 }}"
      
      - name: Print inputs
        run: |
          echo "VAR1=${{ vars.VAR1 }}"
          echo "VAR2=${{ vars.VAR2 }}"
          echo "VAR3=${{ vars.VAR3 }}"
  test-env:
    name: Test Environment Vars
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-environment }}
    steps:
      - name: Print env vars
        run: |
          echo "SECRET1=$SECRET1"
          echo "SECRET2=$SECRET2"
          echo "SECRET3=$SECRET3"
          echo "VAR1=$VAR1"
          echo "VAR2=$VAR2"
          echo "VAR3=$VAR3"
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET2 }}
          SECRET3: ${{ secrets.SECRET3 }}
          VAR1: ${{ vars.VAR1 }}
          VAR2: ${{ vars.VAR2 }}
          VAR3: ${{ vars.VAR3 }}