name: top-level-workflow
on:
  push:
jobs:
  call-level-2:
    name: Second Level Workflow
    uses: ./.github/workflows/second-level-workflow.yml
    with:
      deploy-environment: staging
    secrets:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
      SECRET3: ${{ secrets.SECRET3 }}