name: top-level-workflow
on:
  push:
jobs:
  call-level-2:
    name: Second Level Workflow
    uses: ./.github/workflows/second-level-workflow.yml
    with:
      deploy-environment: staging
    secrets:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
      SECRET3: ${{ secrets.SECRET3 }}
  test-directory:
    name: Test whether consecutive steps run in the same directory
    runs-on: ubuntu-latest
    steps:
      - name: Change directory
        run: |
          ls -al
          cd ./test
          ls -al
          pwd
      
      - name: Check current directory
        run: |
          pwd
          ls -al
