name: top-level-workflow
on:
  push:
jobs:
  process-vars:
    name: Prepare Vars
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      VAR1: ${{ steps.prepare-vars.outputs.VAR1 }}
      VAR2: ${{ steps.prepare-vars.outputs.VAR2 }}
      VAR3: ${{ steps.prepare-vars.outputs.VAR3 }}
    steps:
      - name: Prepare vars
        id: prepare-vars
        run: |
          echo "VAR1=${{ vars.VAR1 }}" >> $GITHUB_OUTPUT
          echo "VAR2=${{ vars.VAR2 }}" >> $GITHUB_OUTPUT
          echo "VAR3=${{ vars.VAR3 }}" >> $GITHUB_OUTPUT
  show-env:
    name: Show Environment
    runs-on: ubuntu-latest
    needs: process-vars
    steps:
      - name: Print secrets
        run: |
          echo "SECRET1=${{ secrets.SECRET1 }}"
          echo "SECRET2=${{ secrets.SECRET2 }}"
          echo "SECRET3=${{ secrets.SECRET3 }}"
      
      - name: Print vars
        run: |
          echo "VAR1=${{ needs.process-vars.outputs.VAR1 }}"
          echo "VAR2=${{ needs.process-vars.outputs.VAR2 }}"
          echo "VAR3=${{ needs.process-vars.outputs.VAR3 }}"
  
  call-level-2:
    name: Second Level Workflow
    uses: ./.github/workflows/second-level-workflow.yml
    needs: [show-env, process-vars]
    with:
      VAR1: ${{ needs.process-vars.outputs.VAR1 }}
      VAR2: ${{ needs.process-vars.outputs.VAR2 }}
      VAR3: ${{ needs.process-vars.outputs.VAR3 }}
    secrets:
      SECRET1: ${{ secrets.SECRET1 }}
      SECRET2: ${{ secrets.SECRET2 }}
      SECRET3: ${{ secrets.SECRET3 }}